services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "${DB_PORT}:5432"
    networks:
      - plainpoints-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: plainpoints_server
    ports:
      - "5000:5000"
    networks:
      - plainpoints-network
    depends_on:
      - db
  
  client:
    build:
      context: ./clientfile
      dockerfile: Dockerfile
    container_name: plainpoints_client
    ports:
      - "3000:3000"
    networks:
      - plainpoints-network
    depends_on:
      - server
      - db
volumes:
  postgres_data:
  Server:
  Client:

networks:
  plainpoints-network:
    driver: bridge
